#!/bin/sh
### BEGIN INIT INFO
# Provides: s0vz
# Required-Start: rc.local
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 1
# Short-Description: S0/Impulse to Volkszaehler 'RaspberryPI deamon'.
#### END INIT INFO

#!/bin/bash

DAEMON="/usr/local/sbin/s0vz"
PIDFILE="/tmp/s0vz.pid" 

test -f $DAEMON || exit 0

case "$1" in

	start)
		test ! -f $PIDFILE || { echo "Deamon already running!"; exit 0; }
		chrt -r 99 su -c $DAEMON pi
		su -c "renice -99 `pidof $DAEMON`" >/dev/null 2>&1
		;;

	stop)
		killall -q s0vz
		rm -f /tmp/s0vz.pid
		;;

	restart)
		$0 stop
		$0 start
		;;

*)
echo "Usage: $0 {start|stop|restart}"
exit 1
;;
esac
